workflows:
  ios-simulator:
    name: iOS Simulator Build (BrowserStack)
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Clean and install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update
      
      - name: Build iOS Simulator app
        script: |
          flutter build ios --debug --simulator
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app
    
    artifacts:
      - build/ios/iphonesimulator/Runner.zip
      - build/ios/iphonesimulator/Runner.app
